apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: interview-bot
  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/part-of: interview-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
