"""extend sessions for intake

Revision ID: ed3b44ec1d0a
Revises: e43290d23bd5
Create Date: 2026-01-22 20:07:57.309726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3b44ec1d0a'
down_revision: Union[str, Sequence[str], None] = 'e43290d23bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("now()"), nullable=False))

    op.add_column('sessions', sa.Column('track', sa.String(length=32), server_default=sa.text("'data'"), nullable=False))
    op.add_column('sessions', sa.Column('mode', sa.String(length=32), server_default=sa.text("'training'"), nullable=False))

    op.add_column('sessions', sa.Column('vacancy_status', sa.String(length=16), server_default=sa.text("'empty'"), nullable=False))
    op.add_column('sessions', sa.Column('vacancy_error', sa.String(length=512), nullable=True))

    op.add_column('sessions', sa.Column('cv_status', sa.String(length=16), server_default=sa.text("'empty'"), nullable=False))
    op.add_column('sessions', sa.Column('cv_error', sa.String(length=512), nullable=True))

    op.add_column('sessions', sa.Column('stage', sa.String(length=16), server_default=sa.text("'collecting'"), nullable=False))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'stage')
    op.drop_column('sessions', 'cv_error')
    op.drop_column('sessions', 'cv_status')
    op.drop_column('sessions', 'vacancy_error')
    op.drop_column('sessions', 'vacancy_status')
    op.drop_column('sessions', 'mode')
    op.drop_column('sessions', 'track')
    op.drop_column('sessions', 'updated_at')
    # ### end Alembic commands ###
